# Generated by Django 5.2.6 on 2025-10-30 19:30

from django.db import migrations

def criar_categorias(apps, schema_editor):
    CategoriaProduto = apps.get_model('food', 'CategoriaProduto')
    categorias_iniciais = ["Lanches", "Bebidas", "Sobremesas", "Combos", "Saladas"]
    for nome in categorias_iniciais:
        CategoriaProduto.objects.get_or_create(nome=nome)

class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_categorias),
    ]
