# Generated by Django 5.2.6 on 2025-10-17 18:52

import food.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', food.models.UsuarioManager()),
            ],
        ),
    ]
