# Generated by Django 5.2.6 on 2025-10-28 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='entregador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
