# Generated by Django 5.2.6 on 2025-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_entrega_entregador_alter_restaurante_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('restaurante', 'Restaurante'), ('entregador', 'Entregador'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
