# Generated by Django 5.2.6 on 2025-10-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_usuario_perfil_delete_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('restaurante', 'Restaurante'), ('entregador', 'Entregador'), ('suporte', 'Suporte')], default='cliente', max_length=20),
        ),
    ]
